### PR TITLE
Update Reference Docs for CLI Tools, APIs and TEAL Specifications

### PR DESCRIPTION
**Pull request by ryanRfox**
This PR updates the script used to generate the following content from source:
- [x] CLI Tools
  - [x] `goal`
  - [x] `algokey`
  - [x] `kmd`
  - [x] `diagcfg`
- [x] REST API Specification
  - [x] `algod`
  - [x] `kmd`
  - [x] `indexer`
- [x] TEAL 
  - [x] Specification 
  - [x] OpCodes

The script was executed against `master` and it updates the relevant content pages.

### CODE REVIEW

**Comment by ryanRfox** [comment]
@wjurayj-algo added documentation for `diagcfg` in #121. This PR intends to automate generation of all available docs from source. It appears that `diagcfg` does not implement the "generate-docs" command similar to the other CLI Tools (e.g. `goal generate-docs /path/to/output`). I left a stub within `reformat-all-commands.sh` for this.

**Comment by ryanRfox** [comment]
Spoke with @wjurayj-algo to better understand the generation process. Checked the code for `goal` and created algorand/go-algorand#1260 to add the `generate-docs` command. 

This PR is now complete with all documentation generated from source. Ready for review.

**Comment by ryanRfox** [comment]
@winder 
  - [ ] Please check my script edits (thanks for the original code)
  - [ ] Please check the output for CLI Tools & REST API Specs
  - [ ] Are there any other places in source we can generate docs for?

@justicz 
  - [ ] Please check the output for TEAL
  - [ ] Are there any other places in source we can generate docs for?

**Comment by winder** [comment]
Looks great @ryanRfox 

The OpenAPI specs are still changing very slightly, so we may need to regenerate again. But the scripts look good and the output looks correct. And nice job digging in and finding the secret cobra option!

One improvement we can make is to use the new OpenAPI parser / codegen tool that we've been working on. We're using it to generate REST Clients for go/java and some test files for unit tests, a module could be created which would generate exactly the markdown file we want and include extra information like cross-linking to transaction / TEAL documentation for fields which hold those objects.

If that sounds like something that you guys would prioritize (after the release, please!) feel free to create a ticket in the backlog.

**Comment by ryanRfox** [comment]
@winder Yes, let's leave this PR open until the spec is "done". It's easy to run the script again to push any updates. It's a _nice to have_ on keeping source and documentation in sync with automation. Let's connect *after* the release to explore what is/not possible/valuable. 

@justicz Do you have time for a quick review this week? Note the tick boxes a couple comments above :)

**Pull request merged**
