### PR TITLE
Add Missing "amount" in Python Complete Example

### PR DESCRIPTION
**Pull request by ImXron**
The complete example was missing a variable (it was referenced in another code snippet above though).

### CODE REVIEW

**Comment by ImXron** [comment]
> I don't see where this variable is used? perhaps if the 100000 value in the txn also uses `amount` instead of directly

Should be that string format on line 238.

**Comment by barnjamin** [comment]
ah right, i missed that. Can you please tweak the transaction create to pass in the amount variable.

I'll get this merged after that

**Comment by ImXron** [comment]
Done! Squashed commits as well.

**Review by ryanRfox — CHANGES_REQUESTED** [review]
I prefer `amount = 100000` be defined within `first_transaction_example(private_key, my_address)` method similar to `note = "Hello World".encode()`, rather than as a global variable. Agree, it's better than hardcoded value. I'm not a fan of modifying the method parameters for this variable addition.

**Review by ryanRfox — APPROVED** [review]
lgtm

**Pull request merged**
