### PR TITLE
Fix/indentation on docs/get details/dapps/pyteal/index

### PR DESCRIPTION
**Pull request by PabloLION**
The indentation in python is critical. I made some fix on the python codeblocks.
Remove: Dollar signs used before commands without showing output by markdown-lint[MD014](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md014)

### CODE REVIEW

**Comment by PabloLION** [comment]
Also after `pip3 install -r requirements.txt` the awesome-page is throwing some error. Please check.(should I create a new issue?)

**Comment by PabloLION** [comment]
I edited the line before fetch. The trailing whitespace caused the conflict

**Review by barnjamin — APPROVED** [review]
thanks!

**Review by barnjamin — APPROVED** [review]

**Comment by PabloLION** [comment]
thanks

**Pull request merged**
