### PR TITLE
Replace node config reference with code generation.

### PR DESCRIPTION
**Pull request by winder**
With https://github.com/algorand/go-algorand/pull/5729 the node config inline documentation is brought into alignment with the developer portal.

This PR uses the `config_json_gen` utility to render the node config reference page from the code comments.

### CODE REVIEW

**Review by ryanRfox — DISMISSED** [review]
looks like it renders properly now. good stuff here

**Comment by nullun** [comment]
Just came across this after manually updating the page in #1186 🤦

**Comment by winder** [comment]
> Just came across this after manually updating the page in #1186 🤦

Ouch. Did the automation do a good job? How do we get the process updated?

**Comment by nullun** [comment]
The script works great! This is far better, thanks Will.

I think ultimately we want it to be run as part of the [release-checker](https://github.com/algorand/docs/blob/staging/.github/workflows/release-checker.yml) workflow so when a new stable release is made (within 30 minutes) it'll PR any new config.md changes, but I'm not familiar with that process atm.

**Review by nullun — COMMENTED** [review]
@winder I added a single function to the code to HTML encode the default values, I have also updated the pr-generator to run this on new releases. Look good?

@ryanRfox Could I get you to take a last look to make sure there's nothing obviously wrong?

Then I'll merge.

**Comment by winder** [comment]
The recent release includes some new data directory configurations. It would be good to wrap up this PR, and run the script again to pull in the new configurations.

cc: @nullun @ryanRfox

**Review by nullun — APPROVED** [review]
Just tested again locally and am all for merging it in. @ryanRfox ?

**Pull request merged**
