### PR TITLE
TEAL3 updates

### PR DESCRIPTION
**Pull request by jannotti**
These are updates to docs for the new TEAL3 opcodes, and also more detail on some opcodes as recommended by the foundation.  One nice change (I think) is that opcodes are now documented with their immediate arguments (for example, substring takes 's' and 'e'.) so now our documentation can refer to those arguments by name to be clearer.

### CODE REVIEW

**Review by ryanRfox — CHANGES_REQUESTED** [review]
I feel this PR should target the `go-algorand` repo rather than `docs`

@jannotti thrilled to see these updates. However, I currently use a script (developed by @winder ) that copies these files from a local build of `go-algorand`. See:
https://github.com/algorand/docs/blob/staging/scripts/reformat-all-commands.sh#L32-L34

I feel it will be more scalable going forward to use this script (DevRel) to build docs from source rather than having to remember (Engineering) to make a PR for updates. 

I don't see these changes in source. I'm looking here (maybe I'm looking at the wrong branch):
https://github.com/algorand/go-algorand/tree/feature/teal3/data/transactions/logic

**Comment by jannotti** [comment]
I was wondering how that worked in the past.  I basically wrote the same script in the Makefile we use to generate those .md files in the first place.  I needed to do it so that I could make a pull request to the algorandfoundation/specs repo, so then I just did the same for the docs repo.  My plan was to `make` and then do the PRs in each. (These changes are not visible yet because they're in jannotti/go-algorand, feature/teal3 branch)

I don't have strong feelings about how we get these PRs made.  Since we have to update the specs repo anyway, this isn't much work for me, and lets me see devrel's thoughts on the changes easily.

**Review by ryanRfox — DISMISSED** [review]
In specifications.md please search replace these changes:
- TEAL_opcodes.md --> opcodes.md
- title: --> #

**Comment by ryanRfox** [comment]
Add new Opcodes and Specification docs for TEAL version 3

**Pull request merged**
