### PR TITLE
fix `\|` in-table render problem

### PR DESCRIPTION
**Pull request by PabloLION**
Reason for using `<code>` tag: https://github.com/mkdocs/mkdocs/issues/2761#issuecomment-1023395978

### CODE REVIEW

**Comment by fionnachan** [comment]
MkDocs supports inline code in tables because it's already using the plugin `tables` in the Python-Markdown lib.
Since the autoformatting that messes up the .md file was caused by prettier, I think `.prettierignore` might be a better choice?

I tested it out on my fork and it works
https://github.com/fionnachan/docs/commit/f09caaf6b055a0d04beee9fa733eb017bb14c1ce
image

**Comment by PabloLION** [comment]
@fionnachan , thanks for the advice.

I didn't clarify that the reason to use `code` tag is to the github page more readable (currently this one https://github.com/algorand/docs/blob/staging/docs/get-details/dapps/avm/teal/specification.md), since github and python-markdown renders <code>\`\\\|\`</code> differently. 

More detailed tests is in the link in the PR note.

**Comment by PabloLION** [comment]
I mean it's not for the auto-formatting(tho its one of the reason) but for how GitHub renders the preview of `.md` files.

**Comment by PabloLION** [comment]
@barnjamin can you review this as well?

**Review by barnjamin — APPROVED** [review]

**Comment by PabloLION** [comment]
I checked @fionnachan 's fork and saw I didnt fix line 201. (I made the new commit after merging...)
I'll create a new PR to fix this.

**Pull request merged**
