### PR TITLE
fixed multisig trx, increased trx amount, added --out filename, added warning message on close out

### PR DESCRIPTION
**Pull request by iskysun96**
https://developer.algorand.org/docs/features/accounts/rekey/

I made the following changes:

- increased transaction microalgos from 1000 to 100000 to prevent minimum balance problem
- added --out filename for creating unsigned txn for rekeying accountA to multisig address
- TEST: SEND WITH AUTH BC_T1 example code wasn't working. changed code to make signing and submitting a transaction from accountA using goal work.

### CODE REVIEW

**Comment by iskysun96** [comment]
Additional change:

- added warning message about close out transaction that clears the rekey connection.

**Review by ryanRfox — DISMISSED** [review]
LGTM

**Comment by iskysun96** [comment]
Additional change:

added warning message about close out transaction that clears the rekey connection on the transaction/structure page under "close an account" section. Seemed appropriate to remind devs about this here as well.

**Comment by barnjamin** [comment]
Is the rekey'd account `--close-to` warning true for assets as well or only Algos? 

`goal asset send` takes a `--close-to` flag as well. I haven't tried it locally but also not sure is some later changes modify the behavior. 

https://developer.algorand.org/docs/reference/cli/goal/asset/send/

**Review by ryanRfox — APPROVED** [review]

**Pull request merged**
